# Generated by Django 5.0.6 on 2024-07-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50)),
                ('line_no', models.IntegerField()),
                ('seq_no', models.IntegerField()),
                ('part_no', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
