# Generated by Django 5.0.6 on 2024-07-15 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodapp', '0004_part_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PartComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_serial_number', models.CharField(max_length=100)),
                ('component_serial_number', models.CharField(max_length=100)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodapp.component')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodapp.part')),
            ],
        ),
    ]
