# Generated by Django 5.0.6 on 2024-07-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodapp', '0005_component_scanned_partcomponent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='scanned',
        ),
    ]
