# Generated by Django 5.0.7 on 2024-07-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodapp', '0006_remove_component_scanned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='creative_date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='component',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
