# Generated by Django 5.0.7 on 2024-07-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodapp', '0009_alter_order_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.CharField(max_length=100),
        ),
    ]
